
version: "3.9"

services:
  nestjs-api:
    container_name: nestjs-api-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: unless-stopped
